apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-jc-nas1200
  namespace: trident
spec:
  version: 1
  backendName: ontap-nas_nassvm_demo_netapp_com
  storageDriverName: ontap-nas
  nasType: nfs
  useREST: true
  name: backend-jc-nas1200
  managementLIF: nassvm-mgmt.demo.netapp.com
  dataLIF: nassvm.demo.netapp.com
  svm: nassvm
  storagePrefix: trident
  autoExportPolicy: false
  autoExportCIDRs:
  - 0.0.0.0/0
  - ::/0
  # labels: ''
  # clientCertificate: ''
  # clientPrivateKey: ''
  # trustedCACertificate: ''
  # limitAggregateUsage: ''
  # limitVolumeSize: ''
  # nfsMountOptions: ''
  qtreesPerFlexvol: '200'
  defaults:
    spaceReserve: none
    spaceAllocation: 'false'
    snapshotPolicy: none
    snapshotReserve: '0'
    unixPermissions: '755'
    snapshotDir: 'true'
    exportPolicy: default
    securityStyle: unix
    encryption: 'false'
    # qosPolicy: ''
    # adaptiveQosPolicy: ''
    # nameTemplate: ''
    # aggregate: ''
  debugTraceFlags:
    api: false
    method: false
  credentials:
    name: trident-creds

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rhoso-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
    argocd.argoproj.io/sync-wave: '5'
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
parameters:
  backendType: ontap-nas
  media: ssd
  provisioningType: thin
  snapshots: 'true'
allowVolumeExpansion: true
volumeBindingMode: Immediate
